spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentcars.kg
    username: postgres
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    path match:
      matching-strategy: ant_path_matcher